# -*- coding: utf-8 -*-
"""TA_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10J5cmu7d55eQOsxjiC1A_avYBGWJJ-ij
"""

"""
TA Tools - Gradio UI
ta_tools.py의 함수들에 웹 UI를 입힌 버전

실행 방법:
    pip install gradio numpy pillow scipy
    python ta_tools_gradio.py
    -> 브라우저에서 http://127.0.0.1:7860 자동으로 열림

같은 폴더에 ta_tools.py 가 있어야 합니다.
"""

import numpy as np
import gradio as gr
from PIL import Image

from ta_tools import (
    heightmap_to_normal,
    pack_channels,
    value_noise,
    voronoi_noise,
    make_seamless,
)


# ============================================================
# 헬퍼: Gradio가 넘겨주는 이미지를 흑백 numpy로 변환
# ============================================================
def to_grayscale(img):
    if img is None:
        return None
    arr = np.array(img)
    if arr.ndim == 3:
        # RGB 또는 RGBA -> luminance 공식으로 흑백 변환
        rgb = arr[..., :3].astype(np.float32)
        gray = 0.299 * rgb[..., 0] + 0.587 * rgb[..., 1] + 0.114 * rgb[..., 2]
        return gray.astype(np.uint8)
    return arr.astype(np.uint8)


def resize_to(arr, target_shape):
    """numpy 배열을 target shape (H, W)로 리사이즈"""
    if arr is None or arr.shape == target_shape:
        return arr
    img = Image.fromarray(arr)
    img = img.resize((target_shape[1], target_shape[0]), Image.BILINEAR)
    return np.array(img)


# ============================================================
# Tab 1: Normal Map
# ============================================================
def ui_normal_map(heightmap, strength, flip_y):
    if heightmap is None:
        return None
    gray = to_grayscale(heightmap)
    return heightmap_to_normal(gray, strength=strength, flip_y=flip_y)


# ============================================================
# Tab 2: Channel Packer
# ============================================================
def ui_channel_packer(r_img, g_img, b_img, a_img):
    inputs = [r_img, g_img, b_img, a_img]
    grays = [to_grayscale(img) for img in inputs]

    # 첫 번째 None 아닌 입력의 사이즈를 기준으로 통일
    ref_shape = None
    for g in grays:
        if g is not None:
            ref_shape = g.shape
            break
    if ref_shape is None:
        return None

    grays = [resize_to(g, ref_shape) for g in grays]
    return pack_channels(r=grays[0], g=grays[1], b=grays[2], a=grays[3])


# ============================================================
# Tab 3: Noise Generator
# ============================================================
def ui_noise(noise_type, size, scale, octaves, num_points, seed):
    size = int(size)
    seed = int(seed)
    if noise_type == "Value (Perlin-like)":
        noise = value_noise(size, scale=scale, octaves=int(octaves), seed=seed)
    else:  # Voronoi
        noise = voronoi_noise(size, num_points=int(num_points), seed=seed)
    return (noise * 255).astype(np.uint8)


# ============================================================
# Tab 4: Seamless Texture
# ============================================================
def ui_seamless(image, blend_ratio):
    if image is None:
        return None, None, None

    arr = np.array(image)
    # RGBA 들어오면 RGB만 사용 (alpha는 별도 처리 필요하면 추후 추가)
    if arr.ndim == 3 and arr.shape[2] == 4:
        arr = arr[..., :3]

    result = make_seamless(arr, blend_ratio=blend_ratio)

    # 2x2 타일링으로 결과 비교
    if arr.ndim == 3:
        tiled_raw = np.tile(arr, (2, 2, 1))
        tiled_seamless = np.tile(result, (2, 2, 1))
    else:
        tiled_raw = np.tile(arr, (2, 2))
        tiled_seamless = np.tile(result, (2, 2))

    return result, tiled_raw, tiled_seamless


# ============================================================
# Gradio Blocks UI
# ============================================================
CSS = """
.gr-button-primary { background: #6366f1 !important; }
footer { display: none !important; }
"""

with gr.Blocks(title="TA Tools", theme=gr.themes.Soft(), css=CSS) as demo:
    gr.Markdown(
        "# 🎨 TA Tools\n"
        "Technical Artist용 텍스처 자동화 툴 모음 — Normal Map / Channel Packer / Noise / Seamless"
    )

    # ----- Tab 1 -----
    with gr.Tab("🗻 Normal Map"):
        gr.Markdown(
            "**흑백 하이트맵 → 노멀맵.** 흰 부분이 튀어나오고 검은 부분이 들어간 정보를 "
            "셰이더가 읽을 수 있는 입체감 데이터로 변환합니다."
        )
        with gr.Row():
            with gr.Column():
                nm_input = gr.Image(label="Heightmap (흑백 이미지)", type="numpy", height=400)
                nm_strength = gr.Slider(0.1, 10.0, value=2.0, step=0.1, label="Strength (굴곡 강도)")
                nm_flip = gr.Checkbox(label="Flip Y (Unreal/DirectX 컨벤션)", value=False)
                nm_btn = gr.Button("Generate", variant="primary")
            with gr.Column():
                nm_output = gr.Image(label="Normal Map", type="numpy", height=400)
        nm_btn.click(ui_normal_map, [nm_input, nm_strength, nm_flip], nm_output)

    # ----- Tab 2 -----
    with gr.Tab("📦 Channel Packer"):
        gr.Markdown(
            "**흑백 4장 → RGBA 한 장.** 비어있는 채널은 검정색으로 채워집니다.\n\n"
            "**일반적 PBR 프리셋**: R=Metallic / G=Roughness / B=AO / A=Height"
        )
        with gr.Row():
            cp_r = gr.Image(label="R channel — Metallic", type="numpy", height=240)
            cp_g = gr.Image(label="G channel — Roughness", type="numpy", height=240)
            cp_b = gr.Image(label="B channel — AO", type="numpy", height=240)
            cp_a = gr.Image(label="A channel — Height", type="numpy", height=240)
        cp_btn = gr.Button("Pack", variant="primary")
        cp_output = gr.Image(label="Packed RGBA (게임 엔진용)", type="numpy", height=400)
        cp_btn.click(ui_channel_packer, [cp_r, cp_g, cp_b, cp_a], cp_output)

    # ----- Tab 3 -----
    with gr.Tab("🌊 Noise Generator"):
        gr.Markdown(
            "**절차적 노이즈 생성.** 셰이더·텍스처의 기본 재료. "
            "파라미터 바꿔가며 어떻게 모양이 변하는지 관찰해보세요."
        )
        with gr.Row():
            with gr.Column():
                n_type = gr.Radio(
                    ["Value (Perlin-like)", "Voronoi"],
                    value="Value (Perlin-like)",
                    label="Noise Type",
                )
                n_size = gr.Slider(128, 1024, value=512, step=64, label="Size (px)")
                n_scale = gr.Slider(2, 32, value=8, step=1, label="Scale (Value: 작을수록 큰 패턴)")
                n_octaves = gr.Slider(1, 8, value=4, step=1, label="Octaves (디테일 레이어 수)")
                n_points = gr.Slider(5, 100, value=30, step=1, label="Voronoi 셀 개수")
                n_seed = gr.Slider(0, 1000, value=42, step=1, label="Seed (난수 시드)")
                n_btn = gr.Button("Generate", variant="primary")
            with gr.Column():
                n_output = gr.Image(label="Noise", type="numpy", height=500)
        n_btn.click(ui_noise, [n_type, n_size, n_scale, n_octaves, n_points, n_seed], n_output)

    # ----- Tab 4 -----
    with gr.Tab("♾️ Seamless Texture"):
        gr.Markdown(
            "**타일링 가능한 텍스처로 변환.** 결과를 2×2로 깔아서 이음새가 사라졌는지 비교할 수 있습니다."
        )
        with gr.Row():
            with gr.Column():
                s_input = gr.Image(label="원본 텍스처", type="numpy", height=400)
                s_blend = gr.Slider(0.05, 0.5, value=0.2, step=0.01, label="Blend ratio (이음새 부드러움)")
                s_btn = gr.Button("Make Seamless", variant="primary")
            with gr.Column():
                s_output = gr.Image(label="Seamless 결과 (단일 타일)", type="numpy", height=400)
        gr.Markdown("### 2×2 타일링 비교")
        with gr.Row():
            s_tiled_raw = gr.Image(label="❌ 원본 2×2 (이음새 보임)", type="numpy")
            s_tiled_new = gr.Image(label="✅ Seamless 2×2 (이음새 없음)", type="numpy")
        s_btn.click(ui_seamless, [s_input, s_blend], [s_output, s_tiled_raw, s_tiled_new])

    gr.Markdown(
        "---\n*결과 이미지는 우측 상단 다운로드 버튼으로 저장할 수 있습니다. "
        "Unity/Unreal 텍스처 슬롯에 그대로 넣어보세요.*"
    )


if __name__ == "__main__":
    demo.launch(inbrowser=True)